/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbc1;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author admin
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_btn = new javax.swing.JButton();
        signpln = new javax.swing.JPanel();
        namelbl = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        idlbl = new javax.swing.JLabel();
        pwdlbl = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        mailtxt = new javax.swing.JTextField();
        maillbl = new javax.swing.JLabel();
        pwdtxt = new javax.swing.JTextField();
        signbtn = new javax.swing.JButton();

        login_btn.setBackground(new java.awt.Color(153, 153, 153));
        login_btn.setFont(new java.awt.Font("Goudy Stout", 1, 11)); // NOI18N
        login_btn.setForeground(new java.awt.Color(51, 153, 255));
        login_btn.setText("LOGIN");
        login_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), java.awt.Color.darkGray, java.awt.Color.lightGray));
        login_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        signpln.setBackground(new java.awt.Color(0, 0, 0));

        namelbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namelbl.setForeground(new java.awt.Color(51, 153, 255));
        namelbl.setText("Enter Name");

        nametxt.setBackground(new java.awt.Color(153, 153, 153));

        idlbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idlbl.setForeground(new java.awt.Color(51, 153, 255));
        idlbl.setText("Enter Rollno");

        pwdlbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pwdlbl.setForeground(new java.awt.Color(51, 153, 255));
        pwdlbl.setText("Enter Password");

        idtxt.setBackground(new java.awt.Color(153, 153, 153));

        mailtxt.setBackground(new java.awt.Color(153, 153, 153));

        maillbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        maillbl.setForeground(new java.awt.Color(51, 153, 255));
        maillbl.setText("Enter E-mail");

        pwdtxt.setBackground(new java.awt.Color(153, 153, 153));

        signbtn.setBackground(new java.awt.Color(153, 153, 153));
        signbtn.setFont(new java.awt.Font("Goudy Stout", 1, 11)); // NOI18N
        signbtn.setForeground(new java.awt.Color(51, 153, 255));
        signbtn.setText("SUBMIT");
        signbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), java.awt.Color.darkGray, java.awt.Color.lightGray));
        signbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signplnLayout = new javax.swing.GroupLayout(signpln);
        signpln.setLayout(signplnLayout);
        signplnLayout.setHorizontalGroup(
            signplnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signplnLayout.createSequentialGroup()
                .addGroup(signplnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signplnLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(signplnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signplnLayout.createSequentialGroup()
                                .addComponent(maillbl, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(signplnLayout.createSequentialGroup()
                                .addComponent(idlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(signplnLayout.createSequentialGroup()
                                .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(signplnLayout.createSequentialGroup()
                                .addComponent(pwdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pwdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(signplnLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(signbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        signplnLayout.setVerticalGroup(
            signplnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signplnLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(signplnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(signplnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(signplnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signplnLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(maillbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signplnLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(mailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(signplnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pwdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(signbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signpln, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signpln, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btnActionPerformed

    private void signbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signbtnActionPerformed
        // TODO add your handling code here:
        String name,mail,pwd;
        int roll;
        name= nametxt.getText();
        mail= mailtxt.getText();
        pwd= pwdtxt.getText();
        roll = Integer.parseInt(idtxt.getText());
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student", "root", "root");
            String query;
            query= "INSERT INTO login(idlogin,name,uname,pwd) VALUES(?,?,?,?);";
            PreparedStatement st=con.prepareStatement(query);
            st.setInt(1, roll);
            st.setString(2, name);
            st.setString(3,mail);
            st.setString(4,pwd);
            st.executeUpdate();
            JOptionPane.showMessageDialog(signpln, "Registered SUCCESSFULLY");
             
             new Login().setVisible(true);
             con.close();
             st.close();
             this.dispose();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
       
    }//GEN-LAST:event_signbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idlbl;
    private javax.swing.JTextField idtxt;
    private javax.swing.JButton login_btn;
    private javax.swing.JLabel maillbl;
    private javax.swing.JTextField mailtxt;
    private javax.swing.JLabel namelbl;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel pwdlbl;
    private javax.swing.JTextField pwdtxt;
    private javax.swing.JButton signbtn;
    private javax.swing.JPanel signpln;
    // End of variables declaration//GEN-END:variables
}
