/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbc1;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author admin
 */
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    static String detail[]=new String[4];
    public Update() {
        initComponents();
         this.setLocationRelativeTo(null);
        idtxt.setText(detail[0]);
        nametxt.setText(detail[1]);
        mailtxt.setText(detail[2]);
        pwdtxt.setText(detail[3]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updatepln = new javax.swing.JPanel();
        pwdtxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();
        nametxt = new javax.swing.JTextField();
        idlbl = new javax.swing.JLabel();
        pwdlbl = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        mailtxt = new javax.swing.JTextField();
        maillbl = new javax.swing.JLabel();
        delbtn = new javax.swing.JButton();
        msglbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        updatepln.setBackground(new java.awt.Color(0, 0, 0));

        pwdtxt.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Enter Name");

        updatebtn.setBackground(new java.awt.Color(153, 153, 153));
        updatebtn.setFont(new java.awt.Font("Goudy Stout", 1, 11)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(51, 153, 255));
        updatebtn.setText("Update");
        updatebtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), java.awt.Color.darkGray, java.awt.Color.lightGray));
        updatebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        nametxt.setBackground(new java.awt.Color(153, 153, 153));

        idlbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idlbl.setForeground(new java.awt.Color(51, 153, 255));
        idlbl.setText("Enter Rollno");

        pwdlbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pwdlbl.setForeground(new java.awt.Color(51, 153, 255));
        pwdlbl.setText("Enter Password");

        idtxt.setBackground(new java.awt.Color(153, 153, 153));

        mailtxt.setBackground(new java.awt.Color(153, 153, 153));

        maillbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        maillbl.setForeground(new java.awt.Color(51, 153, 255));
        maillbl.setText("Enter E-mail");

        delbtn.setBackground(new java.awt.Color(153, 153, 153));
        delbtn.setFont(new java.awt.Font("Goudy Stout", 1, 11)); // NOI18N
        delbtn.setForeground(new java.awt.Color(51, 153, 255));
        delbtn.setText("Delete");
        delbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), java.awt.Color.darkGray, java.awt.Color.lightGray));
        delbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbtnActionPerformed(evt);
            }
        });

        msglbl.setForeground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout updateplnLayout = new javax.swing.GroupLayout(updatepln);
        updatepln.setLayout(updateplnLayout);
        updateplnLayout.setHorizontalGroup(
            updateplnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateplnLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(updateplnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(updateplnLayout.createSequentialGroup()
                        .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(delbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateplnLayout.createSequentialGroup()
                        .addComponent(maillbl, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(updateplnLayout.createSequentialGroup()
                        .addComponent(idlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(updateplnLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(updateplnLayout.createSequentialGroup()
                        .addComponent(pwdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pwdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(msglbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        updateplnLayout.setVerticalGroup(
            updateplnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateplnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(msglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateplnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(updateplnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(updateplnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateplnLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(maillbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(updateplnLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(mailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(updateplnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pwdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updateplnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updatepln, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updatepln, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student", "root", "root");
            Statement st=con.createStatement();
            int id= Integer.parseInt(detail[0]);
            String query="DELETE FROM login WHERE idlogin="+id;
            st.executeUpdate(query);
            st.close();
            String name,mail,pwd;
        int roll;
        name= nametxt.getText();
        mail= mailtxt.getText();
        pwd= pwdtxt.getText();
        roll = Integer.parseInt(idtxt.getText());
            query= "INSERT INTO login(idlogin,name,uname,pwd) VALUES(?,?,?,?);";
            PreparedStatement pst=con.prepareStatement(query);
            pst.setInt(1, roll);
            pst.setString(2, name);
            pst.setString(3,mail);
            pst.setString(4,pwd);
            pst.executeUpdate();
            msglbl.setText("Information Updated successfully");
            JOptionPane.showMessageDialog(updatepln, "Updated SUCCESSFULLY");
             new Login().setVisible(true);
            
            con.close();
            pst.close();
            this.dispose();
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_updatebtnActionPerformed

    private void delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtnActionPerformed
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student", "root", "root");
            Statement st=con.createStatement();
            int id= Integer.parseInt(detail[0]);
            String query="DELETE FROM login WHERE idlogin="+id;
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(updatepln, "Deleted SUCCESSFULLY");
            new Login().setVisible(true);
            
            con.close();
            st.close();
            this.dispose();
        } catch (Exception ex) {
                System.out.println(ex);
        }
    }//GEN-LAST:event_delbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        detail=args;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delbtn;
    private javax.swing.JLabel idlbl;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel maillbl;
    private javax.swing.JTextField mailtxt;
    private javax.swing.JLabel msglbl;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel pwdlbl;
    private javax.swing.JTextField pwdtxt;
    private javax.swing.JButton updatebtn;
    private javax.swing.JPanel updatepln;
    // End of variables declaration//GEN-END:variables
}
